### ISSUE TITLE
[improve] Write logs to a log file.

### ISSUE THREAD

**Issue by rajarshimaitra** [utxo-teleport/teleport-transactions#117]
Instead of using logging in stdout, we should have mechanism to log into a `debug.log` file. 

`debug.log` file should reside in the datadirectory for makers, takers and DNS server.

**Comment by Shourya742** [comment]
@rajarshimaitra For our IT needs, we are satisfied using `env_logger` for logging to stderr. We'll require `log4rs` exclusively for cli apps. Therefore, should we postpone its integration until after the development of the CLI applications? Given that Rust's logging adheres to the facade pattern, transitioning won't involve significant changes. We can simply initialize `log4rs` at the start of the main method in the CLI application, allowing it to use the same `log` crate for file logging.
