### ISSUE TITLE
[improve] Use descriptor wallet in bitcoin core

### ISSUE THREAD

**Issue by rajarshimaitra** [utxo-teleport/teleport-transactions#119]
We are currently using legacy wallets in the bitcoin core rpc here
https://github.com/utxo-teleport/teleport-transactions/blob/36eaaa956d22288e92da4df505bae725e1f037bc/src/wallet/rpc.rs#L93-L108

We are creating a legacy wallet for both the cases.  Change that to descriptor wallet. This might cause changes in our address import. All addresses needs to be turned into raw descriptors before importing. 

Descriptor wallet makes sync faster with rescanblockchain.

**Comment by Jem256** [comment]
Hey @rajarshimaitra I would love to take this on

**Comment by rajarshimaitra** [comment]
Go ahead please..

**Comment by rajarshimaitra** [comment]
>  the test fails with Result::unwrap() on an Err value: Wallet(Rpc(JsonRpc(Rpc(RpcError { code: -4, message: "Only legacy wallets are supported by this command", data: None }))))`

Thats what I meant by changes in address import. If you look at the address importing code (check the line where this error is generating), its using something that is valid only for legacy wallet. That something has to be changed accordingly for descriptor wallet.
