### ISSUE TITLE
test: Unit test for src/utill.rs

### ISSUE THREAD

**Issue by sivasathyaseeelan** [utxo-teleport/teleport-transactions#125]
Issue Description:
This issue highlights the need for unit tests in src/utill.rs file. Currently, some functions in this file are untested, which could lead to potential issues in the future.

Objective:
Write unit tests for the untested functions in the src/utill.rs file.

Details:

Cover all  functions with appropriate test cases.
Ensure tests validate functionality, handle edge cases, and check error conditions.
Integrate the tests into our existing test suite.

**Comment by sivasathyaseeelan** [comment]
I will work on this issue. can anyone please assign me this issue?

**Comment by Shourya742** [comment]
@sivasathyaseeelan The `util.rs` file currently has a test coverage of 95%, which is quite good. Still, there are a few gaps. If you could check out the [code coverage report](https://app.codecov.io/github/utxo-teleport/teleport-transactions/tree/master/src) and work on adding unit tests for those missed areas, that would be great.
