### ISSUE TITLE
feature: Tor

### ISSUE THREAD

**Issue by rajarshimaitra** [utxo-teleport/teleport-transactions#65]
Currently, all communication is happening in clear text. This is extremely bad for privacy.

Makers and Takers should only communicate via Tor. 

Tasks are the following:
- Automatically detect if tor is install and running in the system.
- If not, then download, install and run tor.
- Launch a hidden service for Makers.
- Connect via Tor to Maker's address for Taker.

**Comment by Shourya742** [comment]
Taking is up
