### ISSUE TITLE
test: Unit tests for wallet/fidelity.rs 

### ISSUE THREAD

**Issue by Shourya742** [utxo-teleport/teleport-transactions#79]
**Issue Description:**
This issue highlights the need for unit tests in our `wallet/fidelity.rs` file. Currently, several methods and functions in this file are untested, which could lead to potential issues in the future.

**Objective:**
Write unit tests for each method and associated function in the `wallet/fidelity.rs` file.

**Details:**
- Cover all methods and functions with appropriate test cases.
- Ensure tests validate functionality, handle edge cases, and check error conditions.
- Integrate the tests into our existing test suite.

**Comment by wthrajat** [comment]
After discussion with @rajarshimaitra, most of the methods are now covered by the PR #90 (in both UTs and ITs)
Some methods like `update certificate expiry, find the most valued bond, etc` remains which should be potentially covered in integration tests (issue for future).
This can be closed.
