### ISSUE TITLE
test: Unit test for wallet/rpc.rs

### ISSUE THREAD

**Issue by Shourya742** [utxo-teleport/teleport-transactions#82]
**Issue Description:**
This issue highlights the need for unit tests in our `wallet/rpc.rs` file. Currently, several methods and functions in this file are untested, which could lead to potential issues in the future.

**Objective:**
Write unit tests for each method and associated function in the `wallet/rpc.rs` file.

**Details:**
- Cover all methods and functions with appropriate test cases.
- Ensure tests validate functionality, handle edge cases, and check error conditions.
- Integrate the tests into our existing test suite.

**Comment by rajarshimaitra** [comment]
Theres nothing much to test for rpc, and most stuffs are covered in IT.
