### ISSUE TITLE
[feature] Multiple Wallet Balance API.

### ISSUE THREAD

**Issue by rajarshimaitra** [utxo-teleport/teleport-transactions#91]
Currently the wallet balance API here https://github.com/utxo-teleport/teleport-transactions/blob/dda5c2d9c80cec6ccaec13b5d5038fc10c3a6d53/src/wallet/api.rs#L445-L454

Takes in two booleans to denote whether the balance should include contracts and fidelity bonds. Depending upon these two flags the balance reported would vary. If both are false it will only return the "seedcoin" balance, ie, the balance accumulated in the normal wallet received.

Task: Break the API into 3 separate APIs as per the below category
 - `balance_normal()`: Gives only the normal balance.
 - `balance_swap_settled()`: Gives the total balance accumulated in settled swapcoins.
 - `balance_swap_unstteled()`: Gives the total unsettled swap balance. This should report zero if there is no live contract underway. 
 - `balance_fidelity()`: Gives the fidelity coins balance.
 
 Scope:
 - Define and document the API. This task could lead to possible simplification of the `list_unspent()` API. 
 https://github.com/utxo-teleport/teleport-transactions/blob/dda5c2d9c80cec6ccaec13b5d5038fc10c3a6d53/src/wallet/api.rs#L820C12-L820C36 . The current code internal to list_unspent() is too verbose and can be simplified a lot.
 
 - Add integration test to assert all the balance API is working properly.

**Comment by Shourya742** [comment]
Resolved with #101 and #110
